### ISSUE TITLE
Is it possible to get a colored photo when labeling?

### ISSUE THREAD

**Issue by JuanantonioMG** [bradylowe/labelpc#7]
Hi,
I'm trying to use this tool for labeling some Point Clouds and when loading I only can see a dark image containing only a few white points. Is it possible to get a colored photo when labeling? In my case for labeling it is very important the color.

Thank you in advance!

Juan.

**Comment by bradylowe** [comment]
Hi Juan,

First of all, if you are only seeing a few white points and want to see more, then you can adjust the parameters "scale" and "thickness". By increasing the "scale" parameter, you will make the pixels larger and easier to see (the resolution will be decreased). By increasing the "thickness" parameter, you increase the thickness of each horizontal slice which will result in each slice having more points in it.

As for coloring the points, this is not currently supported but certainly doable by modifying the [bitmapFromSlice](https://github.com/bradylowe/labelpc/blob/d48ba1e0b97acc1405d2ffae3369c0bd2efef2e0/labelpc/pointcloud/Voxelize.py#L212) function. This function currently creates a set of bitmaps from the voxelized point cloud. These bitmaps are one channel, so if the point cloud has 500 x 500 pixels in each slice and 40 slices, then there are 40 bitmaps produced, each with size 500 x 500 x 1. This is a grayscale image. The value of each pixel is either 0 (black) or 255 (white). You can modify this and feed in color information to build 500 x 500 x 3 RGB bitmaps for each slice.

Hope this helps!
Brady.

**Comment by JuanantonioMG** [comment]
Hi Brady,

I think that can help.

Thanks Brady!

Juan.
